# Generated by Django 4.0.6 on 2022-08-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='closet_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='opened_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
